# Link the C runtime statically on Windows so release executables start on a
# clean installation without the Visual C++ redistributable (VCRUNTIME140.dll).
# libjpeg-turbo's static libraries already use the static runtime by default.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
